sudo: required
language: node_js
node_js:
  - "stable"
addons:
  chrome: stable
services:
  - docker
env:
  global:
    CODECOV_TOKEN=$CODECOV_TOKEN
before_script:
  - npm install -g @angular/cli
  - ng build
jobs:
  include:
    - stage: Test Coverage
      script:
        - npm run test-headless
      after_script:
        - bash <(curl -s https://codecov.io/bash)
        - ./node_modules/.bin/codecov ./coverage/helloworld/coverage-final.json;
deploy:
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "hello-world-angular"
  env: "Helloworldangular-env"
  bucket-name: "hello-world-angular2"
  bucket-path: "docker"
  on:
    branch: master
  skip_cleanup: true
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
