language: node_js
node_js:
  - "12.18.3"
dist: trusty
sudo: required
addons:
  chrome: stable
env:
  global:
    CODECOV_TOKEN=$CODECOV_TOKEN
branches:
  only:
  - master
before_script:
  - npm install -g @angular/cli
jobs:
  include:
    - stage: Test Coverage
      script:
        - npm run test-headless
      after_script:
        - ./node_modules/.bin/codecov;
