language: node_js
node_js:
  - "12.18.3"
dist: trusty
sudo: required
addons:
  chrome: stable
services:
  - docker
env:
  global:
    CODECOV_TOKEN=$CODECOV_TOKEN
branches:
  only:
  - master
before_install:
  - docker build .

