language: node_js
node_js:
  - "12.18.3"
dist: trusty
sudo: required
addons:
  chrome: stable
services:
  - docker
env:
  global:
    CODECOV_TOKEN=$CODECOV_TOKEN
branches:
  only:
  - master
before_script:
  - npm install -g @angular/cli
before_install:
  - docker build -t nikanaf/helloworld-angular8 .
jobs:
  include:
    - stage: Test Coverage
      script:
        - npm run test-headless
      after_script:
        - bash <(curl -s https://codecov.io/bash)
        - ./node_modules/.bin/codecov ./coverage/helloworld/coverage-final.json;
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "angular-helloworld"
  env: "Angularhelloworld-env"
  bucket_name: "elasticbeanstalk-us-east-2-054384855372"
  bucket_path: "angular-helloworld"
  on:
      branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
