language: node_js
node_js:
  - "12.18.3"
dist: trusty
sudo: required
addons:
  chrome: stable
services:
  - docker
env:
  global:
    CODECOV_TOKEN=$CODECOV_TOKEN
branches:
  only:
  - master
before_script:
  - npm install -g @angular/cli
  - ng build
jobs:
  include:
    - stage: Test Coverage
      script:
        - npm run test-headless
      after_script:
        - bash <(curl -s https://codecov.io/bash)
        - ./node_modules/.bin/codecov ./coverage/helloworld/coverage-final.json;
deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-simple"
  env: "Dockersimple-env"
  bucket-name: "simple-docker-bucket"
  bucket-path: "docker"
  on:
    branch: master
  skip_cleanup: true
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
